### ISSUE TITLE
Do not crash when `Fqsen` parsing fails

### ISSUE THREAD

**Issue by Ocramius** [Roave/BackwardCompatibilityCheck#134]
As discussed with @sebastianbergmann (https://github.com/sebastianbergmann/phpunit/issues/3718), type annotations like `array<foo, bar>` and other more complex definitions currently lead to the phpdocumentor tooling to throw exceptions.

While it would be good to support these in full, this currently prevents picking up this tool at all in downstream consumers.

The suggestion is therefore to
 1. [x] Suppress `Fqsen` parsing errors
 2. [x] ~~Improve upstream `Fqsen` parsing tooling~~ not needed: see https://github.com/Roave/BackwardCompatibilityCheck/issues/143
 3. [x] ~~Adapt covariance/contravariance checks to support more complex types~~ moved to https://github.com/Roave/BackwardCompatibilityCheck/issues/143
 4. [x] ~~Extract covariance/contravariance checks to a new namespace/library that only does that, making it easier to upgrade its capabilities~~ moved to https://github.com/Roave/BackwardCompatibilityCheck/issues/143

**Comment by Ocramius** [comment]
Incomplete tasks deferred to https://github.com/Roave/BackwardCompatibilityCheck/issues/143
